name: PR

on: pull_request

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common

  validate:
    name: Validate
    needs: setup
    uses: ./.github/workflows/validate.yml

  deploy-preview:
    name: Deploy Netlify preview
    needs: validate
    uses: ./.github/workflows/deploy-to-netlify.yml
    with:
      is_preview: true
      environment: development
