name: PR

on: pull_request

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # validate:
  #   name: Validate
  #   uses: ./.github/workflows/validate.yml

  deploy-preview:
    name: Deploy Netlify preview
    uses: ./.github/workflows/deploy-ui.yml
    with:
      is_preview: true
      environment: development
      REACT_APP_MESSENGER_INVITE_PATH: ${{ vars.REACT_APP_MESSENGER_INVITE_PATH }}
      REACT_APP_VIDEO_ASSETS_PATH: ${{ vars.REACT_APP_VIDEO_ASSETS_PATH }}
      REACT_APP_IMAGE_ASSETS_PATH: ${{ vars.REACT_APP_IMAGE_ASSETS_PATH }}
      REACT_APP_ANDROID_STORE_PATH: ${{ vars.REACT_APP_ANDROID_STORE_PATH }}
      REACT_APP_MATRIX_HOME_SERVER_URL: ${{ vars.REACT_APP_MATRIX_HOME_SERVER_URL }}
      REACT_APP_ZNS_EXPLORER_URL: ${{ vars.REACT_APP_ZNS_EXPLORER_URL }}
      REACT_APP_APPLE_APP_STORE_PATH: ${{ vars.REACT_APP_APPLE_APP_STORE_PATH }}
      REACT_APP_GOOGLE_PLAY_STORE_PATH: ${{ vars.REACT_APP_GOOGLE_PLAY_STORE_PATH }}
      REACT_APP_WEB_APP_DOWNLOAD_PATH: ${{ vars.REACT_APP_WEB_APP_DOWNLOAD_PATH }}
      REACT_APP_MATRIX_HOME_SERVER_NAME: ${{ vars.REACT_APP_MATRIX_HOME_SERVER_NAME }}
    secrets:
      INFURA_URL: ${{ secrets.INFURA_URL }}
      CLOUDINARY_PREFIX: ${{ secrets.CLOUDINARY_PREFIX }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      ETH_CHAIN: ${{ secrets.ETH_CHAIN }}
      ZERO_API_URL: ${{ secrets.ZERO_API_URL }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      WEB3_AUTHENTICATE_MESSAGE: ${{ secrets.WEB3_AUTHENTICATE_MESSAGE }}
      GIPHY_SDK_KEY: ${{ secrets.GIPHY_SDK_KEY }}
      WALLET_CONNECT_PROJECT_ID: ${{ secrets.WALLET_CONNECT_PROJECT_ID }}
      THIRDWEB_CLIENT_ID: ${{ secrets.THIRDWEB_CLIENT_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_NEW }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_NEW }}
