# This is a temporary file, it will be removed in further commits.

name: run-lint
on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-lint:
    runs-on: ubuntu-latest
    env:
      REACT_APP_INFURA_URL: ${{secrets.INFURA_URL}}
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common
      - name: Check code quality
        uses: ./.github/actions/check-code-quality
