name: Validate Changes

on: workflow_call

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common
      - uses: ./.github/actions/check-code-quality
        name: 'Code Quality'
      - uses: ./.github/actions/check-code-validity
        name: 'Code Validity'
